### ISSUE TITLE
Issue with Intel WiFi Card and AirportItlwm on Sequoia...

### ISSUE THREAD

**Issue by fpassold** [MeowyCatCute/ThinkPad_T480_OpenCore_Thunderbolt#1]
About: ThinkPad_T480_OpenCore_Thunderbolt....
Hello. Firstly, thank you for the work you are doing and for making EFIs available. I tested your EFI versions with the recently released Sequoia. They work except for small details... I would like to know more specifically what Wifi/Bluetooth card your Thinkpad T480 uses. Mine is similar to yours, using an Intel AC8265 (WiFi/Bluetooth) and Intel I219-LM board (Ethernet). In addition to a Realtek ALC257 audio card. But I need to use the version with "AirportItlmw" support, because I need to log into a WPA2 Enterprise WiFi network. That is, I cannot use the version with Heliport because I lose this functionality, which is necessary for me. Furthermore, I noticed that after the notebook goes into sleep mode, the audio comes back distorted (low volume, with a kind of reverberation, "echo"). Going into settings and making some audio adjustments sometimes fixes the problem (a slight inconvenience). But the main problem is with the Intel WiFi card. I have been searching on the internet for ways to activate "AirportItlwm" with an Intel card (in my case AC8265) using Sonoma >= 14.4 or Sequoia 15.0, but I am not having success. I appreciate tips/suggestions to try to overcome this problem.

**Comment by MeowyCatCute** [comment]
Audio distortion cannot be reproduced on my end, please try a clean installation.
Re: AirportItlwm support, I do not have the hardware to test _but_ it should be possible to fake your AC8265 to a Broadcom HWID to invoke OCLP patches, then revert to load Sonoma AirportItlwm kext. No support is given because of the reason above.
